package app.zylos.catalog.application.command;

import java.util.List;
import java.util.Objects;

import org.jspecify.annotations.Nullable;

import app.zylos.catalog.domain.vo.CategoryId;
import app.zylos.catalog.domain.vo.ProductAttributes;

/**
 * Request to create a product with at least one variant. The {@code idempotencyKey} is the
 * client-supplied dedup token (enforcement wired with the idempotency store); the
 * resulting {@code ProductId} and per-variant {@code VariantId}s are generated by the application
 * layer, not supplied here.
 */
public record CreateProductCommand(
        String idempotencyKey,
        String name,
        @Nullable String description,
        CategoryId categoryId,
        ProductAttributes attributes,
        List<NewVariant> variants) {

    public CreateProductCommand {
        Objects.requireNonNull(idempotencyKey, "idempotencyKey must not be null");
        Objects.requireNonNull(name, "name must not be null");
        Objects.requireNonNull(categoryId, "categoryId must not be null");
        Objects.requireNonNull(attributes, "attributes must not be null");
        Objects.requireNonNull(variants, "variants must not be null");
        variants = List.copyOf(variants); // immutable; rejects null elements
    }
}
